### ISSUE TITLE
swz68 suffixed pilots

### ISSUE THREAD

**Issue by pakirby1** [CrazyVulcan/x-wing2.0-project-goldenrod#2]
So the naming convention for the same pilot on a different chassis is
Pilotxws-Chassisxws.png.  What chassis are pilots with a swz68 chassis?

![](https://github.com/CrazyVulcan/x-wing2.0-project-goldenrod/blob/main/src/images/En/pilots/poedameron-swz68.png)

**Comment by CrazyVulcan** [comment]
Poe and Snap are both 2 pilots in the same chassis the T70 Xwing so we had to make a new convention for them
